spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/spanner
    username: postgres
    password: Lujianfeng123
  application:
    name: Spanner
  jpa:
    database: PostgreSQL
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  data:
    redis:
      host: localhost
      port: 6379
      password: Lujianfeng123
      database: 0
      connect-timeout: 2000ms
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
          time-between-eviction-runs: 3000ms



server:
  port: 8080

  #MinIO
minio:
  endpoint: http://localhost:9000
  accessKey: root
  secretKey: Lujianfeng123
  bucketName: pic

  #redis


